[package]
name = "llm"
version = "0.1.0"
edition = "2021"


[dependencies]
rag = { path = "../rag" }
serde = "1.0"
serde_json = "1.0"
shared = { path = "../shared" }
tts = { path = "../tts" }
ureq = { version = "2.9.6", features = ["json"] }
